version 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd frontend
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'
